### ISSUE TITLE
Search ?

### ISSUE THREAD

**Issue by KaKi87** [ThomasPe/MS-Store-API#1]
Hello,

I can't find out what is the API endpoint for search, any ideas ?

Thanks.

**Comment by KaKi87** [comment]
up

**Comment by KaKi87** [comment]
up

**Comment by m-doescode** [comment]
Pull request for search is #4 from fork [m-doescode/MS-Store-API - search-documentation](https://github.com/m-doescode/MS-Store-API/tree/search-documentation#search-for-a-product)
