### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by rajvarshu** [ThomasPe/MS-Store-API#10]
Hi,
I tried to integrate into my angular web app but, it's throwing cors issue
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/22830847/208836657-4de290d9-8840-4008-87af-9b118c1607db.png">
Is this API restricted?

**Comment by bribes** [comment]
Nah it’s not restricted CORS is just annoying asf, just need to make a CORS proxy, you can google that online. Just make a web server request it and then make it return with a No CORS header, no too hard.
