### ISSUE TITLE
[FEATURE REQUEST] Making a folder for endpoints

### ISSUE THREAD

**Issue by m-doescode** [ThomasPe/MS-Store-API#5]
I was thinking maybe it's a good idea to organize each endpoint as a file into a folder. Do you think this is a good idea? If you think so, I will be happy to add that to my fork and open a pull request.

**Comment by ThomasPe** [comment]
Absolutely, go ahead. I'm not really actively working on this and don't plan to, but I'm happy to look at improvements anytime!

**Comment by m-doescode** [comment]
#7
